INSERT INTO HOSPITAL (name,city,rating) VALUES ("RADISSON BLU","RANCHI",4.1);
INSERT INTO HOSPITAL (name,city,rating) VALUES ("LE MERIDIAN","KOLKATA",4.32);
INSERT INTO HOSPITAL (name,city,rating) VALUES ("BLUE DIAMOND","BEGUSARAI",3.5);
INSERT INTO HOSPITAL (name,city,rating) VALUES ("LE CHAEFEUR","MUMBAI",4.5);
INSERT INTO HOSPITAL (name,city,rating) VALUES ("HOTEL TAJ","MUMBAI",4.6);